### ISSUE TITLE
[ENHANCEMENT] denoise point cloud data based on local density

### ISSUE THREAD

**Issue by ppa007hot** [python-microscopy/python-microscopy#1558]
In Vutara, it has a nice feature to denoise point cloud data based on local density:
![image_720](https://github.com/user-attachments/assets/fc5395ce-6cb6-4e4c-a0ac-23b4829bf0a7)

Basically, it calculates the nearest neighbors for each point and generates a histogram of each channel and you can filter out sparse localization points (highly likely background noise).

![image_720](https://github.com/user-attachments/assets/a82dda5d-3902-49e0-b83d-29a6853239e6)
![image_720](https://github.com/user-attachments/assets/a8b3c4b5-2998-41ba-8265-77699c6104ac)

This is super helpful when I want to generate iso-surface: the denoised data is less likely to have small non-connected surfaces.

Is it possible to implement this feature in future releases of PYME-Visualize? 

Thank you!

**Comment by barentine** [comment]
@zacsimile is probably better at fielding this, so apologies in advance if I miss something obvious, but I'll have a quick go:
I'll describe something that's already in PYME and maybe you can let us know if that already does what you are looking for? 
1.  You can already estimate the local density for each localization in PYME. From the GUI, go to `View > Estimate Density`.
2. Run that, which will add a datasource to your pipeline recipe, by default it'll be called `dense0`.
3.  Select `dn` in the color-on menu if you want to color each localization by the local density estimate and get a feel for where to later threshold on this density estimate.
4. Click the `Pipeline Recipe` tab, and along the bottom you'll see a button that says `Add Module`, click it, and search or scroll down to `TableFilter` which you'll select and add to the recipe.
5. filter on `dn`
6. Make sure to update the Data Pipeline `output` (top left) points to your filter output, which I named `density_filtered`.
7. Now you can run your isosurface from the Mesh menu and generate it off a density filtered set of localizations.


Here is what your pipeline recipe might look like before the isosurface step, in case you want to copy, paste, and `Apply Text Changes` from the pipeline recipe tab.

```
- localisations.AddPipelineDerivedVars:
    inputEvents: ''
    inputFitResults: FitResults
    outputEventMaps: event_maps
    outputLocalizations: Localizations
- localisations.ProcessColour:
    input: Localizations
    output: colour_mapped
- tablefilters.FilterTable:
    filters:
      error_x:
      - 0
      - 30
    inputName: colour_mapped
    outputName: filtered_localizations
- pointcloud.LocalPointDensity:
    input: filtered_localizations
    input_sample_locations: ''
    output: dense0
- tablefilters.FilterTable:
    filters:
      dn:
      - 0.0
      - 0.01
    inputName: dense0
    outputName: density_filtered

```


<img width="520" alt="Screenshot 2024-11-25 at 1 23 16 PM" src="https://github.com/user-attachments/assets/ca81c22e-14d2-4950-8c94-3bc56be7a0fe">

<img width="564" alt="Screenshot 2024-11-25 at 1 37 20 PM" src="https://github.com/user-attachments/assets/4a9f9481-12ca-415f-9f53-98cf7b7afd99">
