### ISSUE TITLE
[BUG] ProcessColour ocassionally gets wildly too many color channels

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#493]
**Describe the bug**
If you throw a processcolour in front of a densitymapping module, the densitymapping module doesn't see that it's been passed a color-processed tabular type. That wouldn't really bother me, but I occasionally end up with something wild. I'm not yet if that's what's causing this catastrophe, but the print statement is in densitymapping and I wouldn't have expected us to process the color twice
![image](https://user-images.githubusercontent.com/31105780/95505104-cd9a4900-097b-11eb-91dd-28a5bd1680c3.png)

recipe:
![image](https://user-images.githubusercontent.com/31105780/95503339-3a601400-0979-11eb-83a1-1daa3b8500e0.png)

relevant modules
```
- localisations.ProcessColour:
    input: z_mapped
    output: colour_mapped
- localisations.DensityMapping:
    colours:
    - chan0
    - chan1
    inputLocalizations: colour_mapped
    manualXYBounds:
    - 0.0
    - 0.0
    - 30300.0
    - 30300.0
    outputImage: hist
    pixelSize: 25.0
    renderingModule: Histogram
    xyBoundsMode: manual
```

```
'recipe': "- localisations.ProcessColour:\n    input: z_mapped\n    output: colour_mapped\n- tablefilters.FilterTable:\n    filters:\n      A:\n      - 5\n      - 20000\n      LLH:\n      - -250.0\n      - 0.0\n      error_x:\n      - 0\n      - 30\n      error_y:\n      - 0\n      - 30\n      piezoMoving:\n      - -0.5\n      - 0.5\n    inputName: Localizations\n    outputName: filtered_localizations\n- tablefilters.FilterTable:\n    filters:\n      error_x:\n      - 0\n      - 30.0\n      error_y:\n      - 0\n      - 30.0\n    inputName: filtered_localizations\n    outputName: filtered_input\n- multiview.Fold:\n    input_name: filtered_input\n    output_name: folded\n- multiview.ShiftCorrect:\n    input_name: folded\n    output_name: shift_corrected\n    shift_map_path: 'pyme-cluster://villains/CALIBRATION/2020_9_28_reg.sf'\n- multiview.FindClumps:\n    input_name: shift_corrected\n    output_name: with_clumps\n    probe_aware: true\n    radius_offset: 150.0\n- multiview.MergeClumps:\n    input_name: with_clumps\n    output_name: clumped\n- multiview.MapAstigZ:\n    astigmatism_calibration_location: 'pyme-cluster://villains/CALIBRATION/2020_9_28_psf1_astiggauss.am'\n    input_name: clumped\n    output_name: z_mapped\n    rough_knot_spacing: 100.0\n- localisations.AddPipelineDerivedVars:\n    inputEvents: ''\n    inputFitResults: FitResults\n    outputLocalizations: Localizations\n- localisations.DensityMapping:\n    colours:\n    - chan0\n    - chan1\n    inputLocalizations: colour_mapped\n    manualXYBounds:\n    - 0.0\n    - 0.0\n    - 30300.0\n    - 30300.0\n    outputImage: hist\n    pixelSize: 25.0\n    renderingModule: Histogram\n    xyBoundsMode: manual\n
```
Note that this is multiview metadata, non-ratiometric/splitter, so we _should_ have `'probe'` of `0` or `1`.

**Expected behavior**
chan 0 and chan 1 only

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] ubuntu 14.04
 - Python version: 3.6
 - numpy version: 1.14
