### ISSUE TITLE
[BUG] pyme-cluster:// scheme for output modules fails if the directory doesn't exist on the local node

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#759]
**Describe the bug**
![image](https://user-images.githubusercontent.com/31105780/103946806-1db4b300-5105-11eb-9017-31a89b8ff026.png)
![image](https://user-images.githubusercontent.com/31105780/103946856-31f8b000-5105-11eb-832a-2e5d767b4419.png)
![image](https://user-images.githubusercontent.com/31105780/103946891-4046cc00-5105-11eb-9af1-845c90125e0f.png)

for the following recipe
```
- localisations.AddPipelineDerivedVars:
    inputEvents: ''
    inputFitResults: FitResults
    outputLocalizations: input
- tablefilters.FilterTable:
    filters:
      LLH:
      - -250.0
      - 0.0
      error_x:
      - 0.0
      - 20.0
      error_y:
      - 0.0
      - 20.0
    inputName: input
    outputName: filtered
- multiview.Fold:
    input_name: filtered
    output_name: folded
- multiview.CalibrateShifts:
    input_name: folded
    output_name: shiftmap
    search_radius_nm: 500.0
- output.HDFOutput:
    filePattern: '{output_dir}/{file_stub}.sf'
    inputVariables:
      shiftmap: shift_map
    scheme: pyme-cluster://

```
