### ISSUE TITLE
[BUG] writing table from Measure2D generates broken csv and hdf

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#846]
**Describe the bug**
Generated table of measurements with Measure2D module. Saving using the table viewer seems to result in csv and hdf that are unreadable by all readers that I tried.

If these are indeed bugs (and not errors in myusage) then PYME is doing a poor job in preventing and detecting regressions. I know it's hard but this dents confidence. If it is all my fault I'd be happy to learn what the issues area and hang my head in shame.

**To Reproduce**
1. Run yaml recipe (see below)
2. Open generated table and save either in cvs or hdf format
4. Despair trying to read generated files

Question: is there now any other way to save these measurements?

**Expected behavior**
Before I could just open these with excel, pandas csv and hdf readers.

**Screenshots**

Table viewer:

![Screenshot 2021-02-11 at 11 59 30](https://user-images.githubusercontent.com/3750860/107636068-02891600-6c64-11eb-9a83-239740dc0dd5.png)

Unreadable csv in Emacs:

![Screenshot 2021-02-11 at 11 59 48](https://user-images.githubusercontent.com/3750860/107635969-e2f1ed80-6c63-11eb-9529-2a62dd903c26.png)

Unreadable hdf in HDFViewer:

![Screenshot 2021-02-11 at 11 56 24](https://user-images.githubusercontent.com/3750860/107636005-eb4a2880-6c63-11eb-8feb-32f33cfa53b7.png)

**Platform (please complete the following information - or copy-paste from error dialog if shown):**

   -  python-microscopy=20.12.10
   -  python=2.7.17, platform=darwin
   - numpy=1.16.6, wx=3.0.2.0 osx-cocoa (classic)

**Additional context**

yaml recipe
```yaml
- processing.FlexiThreshold:
    inputName: input
    method: fractional
    outputName: thresh
    parameter: 0.8
- processing.BinaryFillHoles:
    inputName: thresh
    outputName: tfilled
- processing.Label:
    inputName: tfilled
    minRegionPixels: 35
    outputName: labels
- measurement.Measure2D:
    inputIntensity: input
    inputLabels: labels
    measureContour: false
    outputName: measurements
```
