### ISSUE TITLE
[BUG] reciperule output_dir seems to drop the last dir

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#967]
**Describe the bug**
pushing a recipe with output modules using {output_dir} context substitution seem to drop the last part of the directory, or not create it, or something. I expect my results to end up in `'Bergamot/2021_2_16/EMC0105H/shell-gmm-ripleys'`, not `'Bergamot/2021_2_16/EMC0105H'`
```
output_dir = 'Bergamot/2021_2_16/EMC0105H/shell-gmm-ripleys'
rulefac = RecipeRuleFactory(recipe=recipe, 
                            inputs={'input': ['pyme-cluster:///' + s for s in inputs]}, 
                            output_dir='pyme-cluster:///' + output_dir)
rulefac.get_rule(context={'input_dir': 'pyme-cluster:///' + posixpath.join(cluster_root, '2021_2_16/EMC0105H')}).push()
```
with 
```
- localisations.ProcessColour:
    input: mapped
    output: colour_mapped
- tablefilters.FilterTable:
    filters:
      A:
      - 5
      - 20000
      error_x:
      - 0
      - 30
      error_y:
      - 0
      - 30
    inputName: colour_mapped
    outputName: filtered_localizations
- localisations.ExtractTableChannel:
    channel: chan0
    inputName: filtered_localizations
    outputName: lamin
- localisations.ExtractTableChannel:
    channel: chan1
    inputName: filtered_localizations
    outputName: coilin
- surface_fitting.SphericalHarmonicShell:
    input_name: lamin
    output_name: harmonic_shell
    output_name_mapped: shell_mapped
- surface_fitting.ImageMaskFromSphericalHarmonicShell:
    input_image_bound_source: coilin
    input_shell: harmonic_shell
    output: shell_mask
    voxelsize_nm:
    - 100.0
    - 100.0
    - 100.0
- localisations.LabelsFromImage:
    inputImage: shell_mask
    inputName: measured
    label_key_name: inside
    outputName: labeled_measured
- pointcloud.GaussianMixtureModel:
    input_points: coilin
    mode: bic
    n: 50
    output_labeled: gmm_label
- localisations.MeasureClusters3D:
    inputName: gmm_label
    labelKey: gmm_label
    outputName: measured
- output.HDFOutput:
    filePattern: '{output_dir}/{file_stub}_gmm_ripleys.hdf'
    inputVariables:
      labeled_measured: clusters
      ripleys_l: ripleys_l
    scheme: pyme-cluster://
- pointcloud.Ripleys:
    inputMask: shell_mask
    inputPositions: coilin_inside
    nbins: 200
    normalization: L
    outputName: ripleys_l
    sampling: 20.0
    three_d: true
- localisations.LabelsFromImage:
    inputImage: shell_mask
    inputName: coilin
    label_key_name: inside
    outputName: shell_coilin
- tablefilters.FilterTable:
    filters:
      inside:
      - 0.5
      - 1.5
    inputName: shell_coilin
    outputName: coilin_inside
- localisations.DensityMapping:
    inputLocalizations: lamin
    outputImage: lamin_hist
    pixelSize: 100.0
    renderingModule: Histogram
- processing.Projection:
    inputName: shell_mask
    kind: Max
    outputName: shell_mask2d
    processFramesIndividually: false
- output.ImageOutput:
    filePattern: '{output_dir}/{file_stub}_lamin_hist.h5'
    inputName: lamin_hist
    scheme: pyme-cluster://
- output.ImageOutput:
    filePattern: '{output_dir}/{file_stub}_shell_mask2d.h5'
    inputName: shell_mask2d
    scheme: pyme-cluster://
- output.HDFOutput:
    filePattern: '{output_dir}/{file_stub}_harmonic_shell.hdf'
    inputVariables:
      harmonic_shell: shell
    scheme: pyme-cluster://
```
